apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic-tap
spec:
  source:
    git:
      url: https://github.com/jaimegag/spring-petclinic-tap.git
      ref:
        branch: main
